from __future__ import annotations

import argparse
import csv
import shutil
import subprocess
import sys
from pathlib import Path

from ultralytics import YOLO


IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
ROOT = Path(__file__).resolve().parent
DATASET_DIR = ROOT / "dataset"
LABELIMG_DIR = ROOT.parent / "labelImg-master"
DEFAULT_LABEL_DIR = DATASET_DIR / "label"
DEFAULT_CLASS_FILE = DATASET_DIR / "predefined_classes.txt"
DEFAULT_FRAME_INDEX = DATASET_DIR / "frame_index.csv"
SOURCE_DIRS = {
    "motion": DATASET_DIR / "motion_candidates",
    "sampled": DATASET_DIR / "sampled_frames",
}
CLASS_NAMES = ["bee"]


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Assist with YOLO annotation for the bee detection dataset."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    status_parser = subparsers.add_parser(
        "status",
        help="Show how many images are labeled and unlabeled.",
    )
    add_common_source_args(status_parser)
    add_common_label_dir_arg(status_parser)

    sync_parser = subparsers.add_parser(
        "sync",
        help="Copy labels from a central label folder back next to matching images.",
    )
    add_common_source_args(sync_parser)
    add_common_label_dir_arg(sync_parser)
    sync_parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing image-side labels if they already exist.",
    )
    sync_parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be copied without writing files.",
    )

    launch_parser = subparsers.add_parser(
        "launch",
        help="Launch labelImg for one source folder.",
    )
    launch_parser.add_argument(
        "--source",
        choices=sorted(SOURCE_DIRS),
        default="motion",
        help="Dataset source folder to annotate.",
    )
    launch_parser.add_argument(
        "--save-dir",
        default=None,
        help="Where labelImg should save YOLO .txt files. Defaults to the source folder.",
    )
    launch_parser.add_argument(
        "--class-file",
        default=str(DEFAULT_CLASS_FILE),
        help="Class list file passed to labelImg.",
    )

    auto_parser = subparsers.add_parser(
        "auto",
        help="Generate YOLO labels automatically with the bee motion model.",
    )
    auto_parser.add_argument(
        "--source",
        choices=sorted(SOURCE_DIRS),
        default="motion",
        help="Dataset source folder to auto-annotate.",
    )
    auto_parser.add_argument(
        "--label-dir",
        default=str(DEFAULT_LABEL_DIR),
        help="Folder where generated YOLO labels should be written.",
    )
    auto_parser.add_argument(
        "--model",
        default=str(ROOT / "bee_motion.pt"),
        help="YOLO model used to generate pseudo-labels.",
    )
    auto_parser.add_argument(
        "--conf",
        type=float,
        default=0.55,
        help="Confidence threshold for auto-annotations.",
    )
    auto_parser.add_argument(
        "--iou",
        type=float,
        default=0.5,
        help="NMS IoU threshold for auto-annotations.",
    )
    auto_parser.add_argument(
        "--max-det",
        type=int,
        default=8,
        help="Maximum detections per image.",
    )
    auto_parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing labels in the output folder.",
    )

    review_parser = subparsers.add_parser(
        "build-review-set",
        help="Create a focused review folder for likely missed blurred bees.",
    )
    review_parser.add_argument(
        "--source",
        choices=sorted(SOURCE_DIRS),
        default="motion",
        help="Dataset source folder to analyze.",
    )
    review_parser.add_argument(
        "--label-dir",
        default=str(DEFAULT_LABEL_DIR),
        help="Folder containing current YOLO labels.",
    )
    review_parser.add_argument(
        "--output-dir",
        default=str(DATASET_DIR / "review_blur_candidates"),
        help="Folder to populate with review images.",
    )
    review_parser.add_argument(
        "--manifest",
        default=str(DATASET_DIR / "review_blur_candidates.csv"),
        help="CSV manifest describing why each image was selected.",
    )
    review_parser.add_argument(
        "--frame-index",
        default=str(DEFAULT_FRAME_INDEX),
        help="CSV metadata generated by extract_training_frames.py.",
    )
    review_parser.add_argument(
        "--model",
        default=str(ROOT / "bee_motion.pt"),
        help="YOLO model used to estimate missed detections.",
    )
    review_parser.add_argument(
        "--review-conf",
        type=float,
        default=0.20,
        help="Low confidence threshold used to hunt for missed blurred bees.",
    )
    review_parser.add_argument(
        "--review-iou",
        type=float,
        default=0.5,
        help="NMS IoU threshold for the review pass.",
    )
    review_parser.add_argument(
        "--max-det",
        type=int,
        default=20,
        help="Maximum detections per image for the review pass.",
    )
    review_parser.add_argument(
        "--top-k",
        type=int,
        default=120,
        help="Number of high-risk images to copy into the review folder.",
    )

    return parser


def add_common_source_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--sources",
        nargs="+",
        choices=sorted(SOURCE_DIRS),
        default=sorted(SOURCE_DIRS),
        help="Source folders to inspect.",
    )


def add_common_label_dir_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--label-dir",
        default=str(DEFAULT_LABEL_DIR),
        help="Folder containing YOLO labels named after image stems.",
    )


def ensure_class_file(path: Path) -> Path:
    content = "\n".join(CLASS_NAMES) + "\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_text(encoding="utf-8") != content:
        path.write_text(content, encoding="utf-8")
    return path


def iter_images(source_dir: Path) -> list[Path]:
    return sorted(
        path for path in source_dir.iterdir()
        if path.is_file() and path.suffix.lower() in IMAGE_EXTENSIONS
    )


def find_label(image_path: Path, label_dir: Path) -> Path | None:
    image_side = image_path.with_suffix(".txt")
    if image_side.exists():
        return image_side

    central_label = label_dir / f"{image_path.stem}.txt"
    if central_label.exists():
        return central_label

    return None


def run_status(source_names: list[str], label_dir: Path) -> int:
    total_images = 0
    total_labeled = 0

    print(f"Central label directory: {label_dir}")
    print("")

    for source_name in source_names:
        source_dir = SOURCE_DIRS[source_name]
        images = iter_images(source_dir)
        labeled = [image for image in images if find_label(image, label_dir)]
        unlabeled = [image for image in images if not find_label(image, label_dir)]

        total_images += len(images)
        total_labeled += len(labeled)

        print(f"{source_name}:")
        print(f"  folder: {source_dir}")
        print(f"  images: {len(images)}")
        print(f"  labeled: {len(labeled)}")
        print(f"  unlabeled: {len(unlabeled)}")
        if unlabeled:
            sample = ", ".join(path.name for path in unlabeled[:5])
            print(f"  sample unlabeled: {sample}")
        print("")

    print("total:")
    print(f"  images: {total_images}")
    print(f"  labeled: {total_labeled}")
    print(f"  unlabeled: {total_images - total_labeled}")
    return 0


def run_sync(
    source_names: list[str],
    label_dir: Path,
    overwrite: bool,
    dry_run: bool,
) -> int:
    if not label_dir.exists():
        raise SystemExit(f"Label directory not found: {label_dir}")

    copied = 0
    skipped = 0
    missing = 0

    for source_name in source_names:
        source_dir = SOURCE_DIRS[source_name]
        ensure_class_file(source_dir / "classes.txt")

        for image_path in iter_images(source_dir):
            central_label = label_dir / f"{image_path.stem}.txt"
            image_label = image_path.with_suffix(".txt")

            if not central_label.exists():
                missing += 1
                continue

            if image_label.exists() and not overwrite:
                skipped += 1
                continue

            if dry_run:
                print(f"would copy {central_label} -> {image_label}")
            else:
                shutil.copy2(central_label, image_label)
            copied += 1

    print(f"copied: {copied}")
    print(f"skipped existing: {skipped}")
    print(f"missing labels: {missing}")
    return 0


def run_launch(source_name: str, save_dir: str | None, class_file: str) -> int:
    image_dir = SOURCE_DIRS[source_name]
    output_dir = Path(save_dir) if save_dir else image_dir
    classes_path = ensure_class_file(Path(class_file))

    if not LABELIMG_DIR.exists():
        raise SystemExit(f"labelImg checkout not found: {LABELIMG_DIR}")

    output_dir.mkdir(parents=True, exist_ok=True)
    if output_dir == image_dir:
        ensure_class_file(output_dir / "classes.txt")

    command = [
        sys.executable,
        str(LABELIMG_DIR / "labelImg.py"),
        str(image_dir),
        str(classes_path),
        str(output_dir),
    ]

    print("Launching labelImg...")
    print(f"  images: {image_dir}")
    print(f"  save dir: {output_dir}")
    print(f"  classes: {classes_path}")
    return subprocess.call(command, cwd=LABELIMG_DIR)


def write_yolo_label(
    target_path: Path,
    boxes_xyxy: list[tuple[float, float, float, float]],
    image_width: int,
    image_height: int,
) -> None:
    lines: list[str] = []
    for x1, y1, x2, y2 in boxes_xyxy:
        x_center = ((x1 + x2) / 2.0) / image_width
        y_center = ((y1 + y2) / 2.0) / image_height
        width = (x2 - x1) / image_width
        height = (y2 - y1) / image_height
        lines.append(f"0 {x_center:.6f} {y_center:.6f} {width:.6f} {height:.6f}")

    content = "\n".join(lines)
    if content:
        content += "\n"
    target_path.write_text(content, encoding="utf-8")


def run_auto(
    source_name: str,
    label_dir: Path,
    model_path: Path,
    conf: float,
    iou: float,
    max_det: int,
    overwrite: bool,
) -> int:
    source_dir = SOURCE_DIRS[source_name]
    if not model_path.exists():
        raise SystemExit(f"Model not found: {model_path}")

    label_dir.mkdir(parents=True, exist_ok=True)
    ensure_class_file(label_dir / "classes.txt")
    ensure_class_file(DEFAULT_CLASS_FILE)

    model = YOLO(str(model_path))
    images = iter_images(source_dir)

    predicted = 0
    skipped = 0
    empty = 0
    total_boxes = 0

    for image_path in images:
        label_path = label_dir / f"{image_path.stem}.txt"
        if label_path.exists() and not overwrite:
            skipped += 1
            continue

        result = model.predict(
            source=str(image_path),
            conf=conf,
            iou=iou,
            max_det=max_det,
            verbose=False,
        )[0]

        if result.boxes is None or len(result.boxes) == 0:
            empty += 1
            continue

        height, width = result.orig_shape
        boxes: list[tuple[float, float, float, float]] = []
        for box in result.boxes:
            x1, y1, x2, y2 = box.xyxy[0].tolist()
            x1 = min(max(x1, 0.0), width)
            y1 = min(max(y1, 0.0), height)
            x2 = min(max(x2, 0.0), width)
            y2 = min(max(y2, 0.0), height)
            if x2 <= x1 or y2 <= y1:
                continue
            boxes.append((x1, y1, x2, y2))

        if not boxes:
            empty += 1
            continue

        write_yolo_label(label_path, boxes, width, height)
        predicted += 1
        total_boxes += len(boxes)

    print(f"source: {source_dir}")
    print(f"label dir: {label_dir}")
    print(f"model: {model_path}")
    print(f"predicted labels: {predicted}")
    print(f"skipped existing: {skipped}")
    print(f"images with no detections: {empty}")
    print(f"total boxes written: {total_boxes}")
    return 0


def load_frame_index(frame_index_path: Path) -> dict[str, dict[str, float | str]]:
    if not frame_index_path.exists():
        return {}

    metadata: dict[str, dict[str, float | str]] = {}
    with frame_index_path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            filename = row.get("filename")
            if not filename:
                continue
            metadata[filename] = {
                "video": row.get("video", ""),
                "kind": row.get("kind", ""),
                "motion_score": float(row["motion_score"]) if row.get("motion_score") else 0.0,
                "sharpness": float(row["sharpness"]) if row.get("sharpness") else 0.0,
                "frame": int(row["frame"]) if row.get("frame") else -1,
            }
    return metadata


def count_label_lines(label_path: Path) -> int:
    if not label_path.exists():
        return 0

    with label_path.open("r", encoding="utf-8") as handle:
        return sum(1 for line in handle if line.strip())


def clear_directory(directory: Path) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    for child in directory.iterdir():
        if child.is_file():
            child.unlink()


def run_build_review_set(
    source_name: str,
    label_dir: Path,
    output_dir: Path,
    manifest_path: Path,
    frame_index_path: Path,
    model_path: Path,
    review_conf: float,
    review_iou: float,
    max_det: int,
    top_k: int,
) -> int:
    source_dir = SOURCE_DIRS[source_name]
    if not model_path.exists():
        raise SystemExit(f"Model not found: {model_path}")

    frame_index = load_frame_index(frame_index_path)
    model = YOLO(str(model_path))
    images = iter_images(source_dir)

    rows: list[dict[str, str | int | float]] = []
    for image_path in images:
        label_path = label_dir / f"{image_path.stem}.txt"
        current_count = count_label_lines(label_path)

        result = model.predict(
            source=str(image_path),
            conf=review_conf,
            iou=review_iou,
            max_det=max_det,
            verbose=False,
        )[0]
        review_count = 0 if result.boxes is None else len(result.boxes)

        meta = frame_index.get(image_path.name, {})
        sharpness = float(meta.get("sharpness", 0.0))
        motion_score = float(meta.get("motion_score", 0.0))
        missing_hint = max(0, review_count - current_count)
        blur_penalty = max(0.0, 25.0 - sharpness)
        risk_score = (missing_hint * 10.0) + blur_penalty + (motion_score * 2.0)

        rows.append({
            "filename": image_path.name,
            "image_path": str(image_path),
            "label_path": str(label_path),
            "current_label_count": current_count,
            "review_detection_count": review_count,
            "possible_missing": missing_hint,
            "sharpness": round(sharpness, 2),
            "motion_score": round(motion_score, 4),
            "risk_score": round(risk_score, 2),
        })

    rows.sort(
        key=lambda row: (
            float(row["risk_score"]),
            int(row["possible_missing"]),
            -float(row["sharpness"]),
        ),
        reverse=True,
    )

    selected = rows[: min(top_k, len(rows))]
    clear_directory(output_dir)
    for row in selected:
        src = Path(str(row["image_path"]))
        shutil.copy2(src, output_dir / src.name)

    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    with manifest_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "filename",
                "current_label_count",
                "review_detection_count",
                "possible_missing",
                "sharpness",
                "motion_score",
                "risk_score",
                "image_path",
                "label_path",
            ],
        )
        writer.writeheader()
        writer.writerows(selected)

    print(f"source: {source_dir}")
    print(f"review folder: {output_dir}")
    print(f"manifest: {manifest_path}")
    print(f"selected images: {len(selected)}")
    if selected:
        print(f"top candidate: {selected[0]['filename']}")
    return 0


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    if args.command == "status":
        return run_status(args.sources, Path(args.label_dir))

    if args.command == "sync":
        return run_sync(
            args.sources,
            Path(args.label_dir),
            overwrite=args.overwrite,
            dry_run=args.dry_run,
        )

    if args.command == "launch":
        return run_launch(
            args.source,
            save_dir=args.save_dir,
            class_file=args.class_file,
        )

    if args.command == "auto":
        return run_auto(
            args.source,
            Path(args.label_dir),
            Path(args.model),
            conf=args.conf,
            iou=args.iou,
            max_det=args.max_det,
            overwrite=args.overwrite,
        )

    if args.command == "build-review-set":
        return run_build_review_set(
            args.source,
            Path(args.label_dir),
            Path(args.output_dir),
            Path(args.manifest),
            Path(args.frame_index),
            Path(args.model),
            review_conf=args.review_conf,
            review_iou=args.review_iou,
            max_det=args.max_det,
            top_k=args.top_k,
        )

    parser.error(f"Unsupported command: {args.command}")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
